In [11]:
import cv2 as cv2
import numpy as np
from IPython.display import Image 

1. Download the peppers image from this link https://blogs.mathworks.com/images/loren/173/peppers_BlueHills.png. Return a binary image (only 0s and 1s), with 1s corresponding to only the yellow peppers. Do this by setting a minimum and maximum threshold value on pixel values in the R,G,B channels. Note that you won’t be able to perfectly capture the yellow peppers, but give your best shot!

In [13]:
Image(url="peppers.png", width=300, height=300) 

In [17]:
#read an image  
image=cv2.imread('peppers.png')

#treshold=[90,180,220]
treshold=[90,190,150]
for i in range(image.shape[0]):
    for j in range(image.shape[1]):
        colors=image[i,j,:]
        #print(colors)
        if colors[0]<treshold[0] and colors[1]>treshold[1] and colors[2]>treshold[0]:
            image[i,j,:]=[255,255,255]
        else:
            image[i,j,:]=[0,0,0]
        
        
           


In [18]:
cv2.imshow('image',image)
# Espera una tecla para cerrar la ventana
cv2.waitKey(0)

# Cierra todas las ventanas abiertas
cv2.destroyAllWindows()

In [21]:
Image(url="peppers_binary.png", width=300, height=300) 

While RGB is the most common color space for images, it is not the only one. For example, one popular color space is HSV (Hue-Saturation-Value). Hue encodes color, value encodes lightness/darkness, and saturation encodes the intensity of the color. For a visual, see Fig. 1 of this wiki article https://en.wikipedia.org/wiki/HSL_and_HSV. Convert the image to the HSV color space using OpenCV’s cvtColor() function, and try to perform the same task by setting a threshold in the Hue channel. Add both binary images to your report. Which colorspace was easier to work with for this task, and why?

In [31]:
image=cv2.imread('peppers.png')
#converto hsv color space
image=cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

#define the range of yellow color in HSV
lower_yellow = np.array([20, 100, 240])
upper_yellow = np.array([60, 255, 255])

# Threshold the HSV image to get only yellow colors
mask = cv2.inRange(image, lower_yellow, upper_yellow)

# Bitwise-AND mask and original image
res = cv2.bitwise_and(image,image, mask= mask)

cv2.imshow('res',res)
cv2.imshow('mask',mask)
cv2.imshow('image',image)
# Espera una tecla para cerrar la ventana
cv2.waitKey(0)

# Cierra todas las ventanas abiertas
cv2.destroyAllWindows()



In [32]:
Image(url="peppers_hsv.png", width=300, height=300) 

Write separate functions that output the 3 x 3 transformation matrices for the following
transforms: translation, rotation, similarity (translation, rotation, and scale), and affine. The
functions should take as input the following arguments

1. Translation: horizontal and vertical displacements
2. Rotation: angle
3. Similarity: angle, horizontal/vertical displacements, and scale factor (assume equal scaling for horizontal and vertical dimensions)
4. Affine: 6 parameters

The output of each function will be a 3 x 3 matrix.

In [38]:
def traslation_matrix_2d(traslation_x, traslation_y):
    return np.array([[1,0,traslation_x],[0,1,traslation_y],[0,0,1]])

def rotation_matrix_2d(angle):
    return np.array([[np.cos(angle),-np.sin(angle),0],[np.sin(angle),np.cos(angle),0],[0,0,1]])

def similarity_matrix_2d(traslation_x, traslation_y, angle,scale_factor):
    traslation_matrix=traslation_matrix_2d(traslation_x, traslation_y)
    rotation_matrix=rotation_matrix_2d(angle)
    scale=np.array([[scale_factor,0,0],[0,scale_factor,0],[0,0,1]])
    return np.dot(traslation_matrix,np.dot(rotation_matrix,scale))

def affine_matrix_2d(traslation_x, traslation_y, angle,scale_factor,shear_factor_x,shear_factor_y):
    similarity=similarity_matrix_2d(traslation_x, traslation_y, angle,scale_factor)
    shear=np.array([[1,shear_factor_x,0],[shear_factor_y,1,0],[0,0,1]])
    return np.dot(similarity,shear)

In [35]:
tmatrix=traslation_matrix_2d(100, 67)
print(tmatrix)

[[  1   0 100]
 [  0   1  67]
 [  0   0   1]]


In [36]:
tmatrix=rotation_matrix_2d(np.pi/3)
print(tmatrix)

[[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]


In [40]:
amatrix=affine_matrix_2d(10, 10, np.pi,0.5,0.3,0.8)
print(amatrix)

[[-0.5  -0.15 10.  ]
 [-0.4  -0.5  10.  ]
 [ 0.    0.    1.  ]]
